### ISSUE TITLE
fpm children dying

### ISSUE THREAD

**Issue by cgtx** [iuscommunity-pkg/php56u#11]
When the `session.save_path` is set to `/var/lib/php-fpm/session` in `www.conf`, it results in the fpm children erroring out.

```
[20-Jan-2015 15:00:38] WARNING: [pool www] child 29962 exited on signal 11 (SIGSEGV) after 2.397379 seconds from start
```

I tried to change this to `/var/lib/php/fpm/session`, but it didn't work.  I tried multiple combinations of users of the fpm children processes (apache/php-fpm), and different ownership of the directories.  It appears that there is something special about `/var/lib/php-fpm` that is causing the issue.

I changed the value to `/var/lib/fpm/session` and everything works.

https://github.com/iuscommunity-pkg/php56u/blob/f9b787a33fe3c3be747f7e96d028b22e3555bfb5/SOURCES/php-fpm-www.conf#L225-226
https://github.com/iuscommunity-pkg/php56u/blob/f9b787a33fe3c3be747f7e96d028b22e3555bfb5/SPECS/php56u.spec#L1438-1439
https://github.com/iuscommunity-pkg/php56u/blob/f9b787a33fe3c3be747f7e96d028b22e3555bfb5/SPECS/php56u.spec#L1712-1713

**Comment by cgtx** [comment]
Mostly caused by this commit. cb6112ec7121eb2bf86fb44d88fda8f187ec4ae3

**Comment by ralfbecker** [comment]
Is this bug-report the reason 5.6.17 is still in testing?

Ralf

**Comment by b-harper** [comment]
Hey @ralfbecker,

This issue is not effecting the php56u-5.6.17  (or previous versions) release schedule.    Our standard is to keep packages in the [testing repositories for two week] before moving them to the stable repositories.  PHP 5.6.17 got released on January 7th, but we did not get packages made till January 8th.  The two week mark will be on January 22nd, but we don't like pushing changes to the stable repositories on Friday.  We will move the php56u-5.6.17 packages to the stable repositories on  January 25th.  

-Ben

[0]: https://ius.io/Philosophy/#release-policy

**Comment by ralfbecker** [comment]
Hey Ben,

thanks for the info about your policy :-)

I had a quick check myself with --enablerepo ius-testing and it looks ok to me.

I'll wait for the 25th.

Ralf

**Comment by b-harper** [comment]
@ralfbecker, you are welcome and thanks for the feedback.

**Comment by carlwgeorge** [comment]
I can no longer reproduce this issue.  Best guess is it must have been fixed upstream.
