### ISSUE TITLE
example configuration can break site when upgrades occur

### ISSUE THREAD

**Issue by linepoint** [iuscommunity-pkg/php56u#18]
The example configuration file /etc/php-fpm.d/www.conf that is provided gets reinstalled and attempted to load upon upgrades if it doesn't exist.

This can break sites when there's a conflict (eg: listening ip/port conflict) which stops php-fpm from restarting correctly.  Or if there's no conflict, a new running service is now active which can have security implications.

The easy fix would be to just rename the file from www.conf to www.conf.sample so it doesn't auto load.

**Comment by carlwgeorge** [comment]
The /etc/php-fpm.d/www.conf file isn't just an example, it is the default pool configuration.  If we don't load it, php-fpm will fail to start out of the box.

```
[root@test7 php-fpm.d]# mv www.conf www.conf.sample
[root@test7 php-fpm.d]# systemctl start php-fpm.service 
Job for php-fpm.service failed because the control process exited with error code. See "systemctl status php-fpm.service" and "journalctl -xe" for details.
[root@test7 php-fpm.d]# cat /var/log/php-fpm/error.log 
[03-Jun-2016 14:46:38] ERROR: No pool defined. at least one pool section must be specified in config file
[03-Jun-2016 14:46:38] ERROR: failed to post process the configuration
[03-Jun-2016 14:46:38] ERROR: FPM initialization failed
```

I remember seeing a similar issue with httpd in the past.  If you try to disable the default welcome page by deleting the welcome.conf file, it would later get recreated when httpd got updated.  The best way to work around this is to leave the file in place but delete or comment out the contents.  The edited file won't get overwritten by updates because it is marked as `config(noreplace)` in the spec file.

Likewise with php-fpm, if you don't want to use the default www.conf file, replacing it with an empty file should take care of this for you.
